server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: https://dle.dev.smartclide.eu
          predicates:
            - Path=/api/dle
          filters:
            - SetPath=/api
        - id: route2
          uri: https://rmv.dev.smartclide.eu
          predicates:
            - Path=/api/rmv
          filters:
            - SetPath=/api