server:
  port: 9090
eu:
  smartclide:
    api:
      host: localhost
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-smartclide-che.che.smartclide.eu/auth/realms/che
  cloud:
    gateway:
      routes:
        - id: typicode
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/typicode/**
          filters:
            - RewritePath=/typicode/?(?<segment>.*), /$\{segment}
        - id: petstore
          uri: https://petstore.swagger.io
          predicates:
            - Path=/petstore/**
          filters:
            - RewritePath=/petstore/?(?<segment>.*), /v2/$\{segment}
        - id: rest_websocket
          uri: http://${eu.smartclide.api.host}:8080
          predicates:
            - Path=/mom/**
        - id: websocket
          uri: ws://${eu.smartclide.api.host}:8080
          predicates:
            - Path=/websocket